version: 2
project_name: build.go

builds:
  - skip: true

release:
  prerelease: auto

archives:
  - id: docs
    files:
      - LICENSE
      - README.md

checksum:
  name_template: 'checksums.txt'

sboms:
  - id: lib